version: '3.8'
services:
  web:
    build: .
    container_name: flask-proyecto-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/app.py  # Ruta completa incluyendo la carpeta 'app'
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sistema_inventario_BD
      - DB_USER=postgres
      - DB_PASSWORD=Americ@1927
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sistema_inventario_BD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Americ@1927
    ports:
      - "5432:5432"
    volumes:
      - ./path_to_sql_init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
